updated chart uri for nodered v0.0.2
openshift-helm-charts/charts pull request #391
Opened 2022-01-13 14:17 UTC by prajyotNarulkar925

2022-01-14 13:13 UTC, dperaza4dustbit requested changes

2022-01-14 13:13 UTC, dperaza4dustbit commented on index.yaml
> +    - https://github.com/rhm-samples/edge-helm-charts/blob/master/nodered-chart-0.0.2.tgz?raw=true
This change is correct, but does not match what the report for 0.0.2 version has, lets remove this change here and send another PR for 0.0.3 version with the new url in the report.

2022-01-14 13:13 UTC, dperaza4dustbit commented on index.yaml
> -    version: 0.0.1
I would only remove a version like this if it is something bad like a security issue or something serious like that, if it merely does not work, I would not worry too much about have older versions of a chart that does not work.

2023-04-19 18:23 UTC, komish commented
Closing this PR due to its age. Please re-submit if you wish to make further changes.

2023-04-19 18:23 UTC, closed without merging